version: "3.9"

services:
  # Контейнер базы данных
  postgres:
    image: postgres:15
    container_name: data-base-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранение данных
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Контейнер парсера
  data-parser:
    build:
      context: .  # Путь к Dockerfile
      dockerfile: Dockerfile
    container_name: parser-container
    depends_on:
      - postgres
    networks:
      - app-network
    healthcheck: # Проверка на завершение работы
      test: [ "CMD-SHELL", "pgrep -f main.py || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  # Контейнер анализа данных
  analysis:
    build:
      context: ./analytics  # Путь к Dockerfile для Jupyter
      dockerfile: Dockerfile
    container_name: analysis-container
    depends_on:
      postgres:  # Зависимость от PostgreSQL-контейнера
        condition: service_started
      data-parser: # Зависимость от парсинг-контейнера
        condition: service_healthy  # Ждём состояния
    volumes:
      - ./output:/home/jovyan/analytics/output  # Монтируем папку для вывода HTML-результата
    ports:
      - "8888:8888"  # Открываем порт для Jupyter
    networks:
      - app-network
    command: >
      bash -c "
        jupyter nbconvert --to html --template=classic /home/jovyan/analytics/analytics.ipynb --output /home/jovyan/analytics/output/output.html
      "


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:  # Том для хранения данных